version: '3.8'

services:
  # Serviço do Ganache:
  ganache:
    image: trufflesuite/ganache:v7.9.2
    container_name: ganache
    ports:
      - "8545:8545"
    command: 
      - --host=0.0.0.0
      - --port=8545
      - --deterministic # Gera as Mesmas Contas e Chaves Privadas, Na Mesma Ordem (De Forma Determinística).
      - --chain.vmErrorsOnRPCResponse=true # Mostra os Erros Reais da Máquina Virtual Ethereum nas Respostas.
      - --wallet.totalAccounts=10
      - --wallet.defaultBalance=100
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Serviço do Administrador/Owner da Blockchain Ganache:
  owner:
    build:
      context: ./owner
      dockerfile: Dockerfile
    container_name: owner
    depends_on:
      - ganache
    env_file:
      - ./owner/.env
    volumes:
      - ./build:/app/build # Permite Acessar os ABIs e Bytecodes Compilados.
    network_mode: host
  
  # Serviço do Broker MQTT, Mosquitto:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # Serviço da API do Servidor "EcoCharge":
  ecocharge:
    build:
      context: ./ev_recharging_servers/ecocharge
      dockerfile: Dockerfile
    container_name: ecocharge_server
    depends_on:
      - ganache
      - owner
      - mosquitto
    env_file:
      - ./ev_recharging_servers/ecocharge/.env
    volumes:
      - ./build:/app/build
    network_mode: host
    restart: always
