version: '3.8'

services:
  # Serviço do Ganache:
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    env_file:
      - ./ganache/.env
    ports:
      - "8545:8545"
    command: ["ganache-cli", "--host", "${GANACHE_HOST}", "--port", "${GANACHE_PORT}", "-d"] # "-d" Gera as Mesmas Contas e Chaves Privadas, Na Mesma Ordem (De Forma Determinística).
    network_mode: host
    restart: always

  # Serviço da API do Servidor "EcoCharge":
  ecocharge:
    build:
      context: ./ev_recharging_servers/ecocharge
      dockerfile: Dockerfile
    container_name: ecocharge_server
    depends_on:
      - ganache
    env_file:
      - ./ev_recharging_servers/ecocharge/.env
    volumes:
      - ./compiled_contracts:/app/contracts # Permite Acessar o ABI e Bytecode Compilados.
    network_mode: host
    restart: always
